---
permalink: online-help/concept-monitoring-vms.html 
sidebar: sidebar 
keywords: virtual machines 
summary: 'En caso de cualquier problema de latencia en las aplicaciones de máquinas virtuales \(VM\), es posible que deba supervisar las VM para analizar y solucionar la causa.' 
---
= Supervisar máquinas virtuales
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para cualquier problema de latencia en las aplicaciones de máquinas virtuales (VM), es posible que deba supervisar las VM para analizar la causa y solucionar los problemas de ella.

Active IQ Unified Manager permite ver la topología detallada de una aplicación de VM que muestra los componentes a los que está relacionada el equipo virtual, por ejemplo, el host de la máquina virtual o el almacén de datos que está conectado. La vista de topología muestra los componentes subyacentes en sus capas específicas, en el siguiente orden: *Disco virtual* > *VM* > *Host* > *Red* > *Datastore* > *VMDK*.

[NOTE]
====
Para ver las métricas del almacén de datos (en la capa de almacenamiento), se debe añadir el clúster de ONTAP primario a Unified Manager y se debe completar la detección (sondeo o colección de métricas) del clúster.

====
Puede determinar la ruta de I/o y las latencias de los componentes desde un aspecto topológico e identificar si el almacenamiento es la causa del problema de rendimiento. La vista de resumen de la topología muestra la ruta de I/o y resalta el componente que tiene problemas de IOPS y latencia para que pueda decidir los pasos para la solución de problemas. También puede tener una vista ampliada de la topología que representa cada componente por separado junto con la latencia de ese componente. Puede seleccionar un componente para determinar la ruta de I/o resaltada en las capas.



== Programación de recogida de datos de vCenter

Para los datos de configuración de vCenter, Unified Manager sigue la misma programación que para recoger datos de configuración del clúster. Para obtener información sobre la configuración de vCenter y la programación de recogida de datos de rendimiento, consulte "actividad de recopilación de datos de rendimiento y configuración del clúster".

VCenter recopila muestras de datos de rendimiento en tiempo real de 20 segundos y las enrolla en muestras de hasta 5 minutos. La programación para la recogida de datos de rendimiento de Unified Manager se basa en la configuración predeterminada de vCenter Server. Unified Manager procesa las muestras de 5 minutos obtenidas de vCenter y calcula una media por hora de las IOPS y la latencia de los discos virtuales, los equipos virtuales y los hosts. Para los almacenes de datos, Unified Manager calcula un promedio por hora de IOPS y latencia de muestras obtenidas de ONTAP. Estos valores están disponibles en la parte superior de la hora. Las métricas de rendimiento no están disponibles inmediatamente después de añadir una instancia de vCenter, y solo están disponibles cuando se inicia la siguiente hora. El sondeo de los datos de rendimiento comienza a completar un ciclo de recogida de datos de configuración.



== Visualización de la topología de resumen

Para determinar los problemas de rendimiento, vea las máquinas virtuales en una topología de resumen

. Vaya a *VMWARE* > *Máquinas virtuales*.
. Busque su máquina virtual escribiendo su nombre en el cuadro de búsqueda. También puede filtrar los resultados de la búsqueda según criterios específicos haciendo clic en el botón *filtro*. Sin embargo, si no puede encontrar la máquina virtual, asegúrese de que se haya añadido y detectado la instancia correspondiente de vCenter.
+
[NOTE]
====
Los servidores vCenter permiten caracteres especiales (como %, &, *, $, #, @, !, \, /, :, *, ?, "', <, >, |, ;, ') en los nombres de entidades vSphere, como VM, cluster, datastore, carpeta, o archivo. VMware vCenter Server y ESX/ESXi Server no escapan a los caracteres especiales utilizados en los nombres mostrados. Sin embargo, cuando se procesa el nombre en Unified Manager, se muestra de forma diferente. Por ejemplo, una máquina virtual llamada como `%$VC_AIQUM_clone_191124%` En vCenter Server se muestra como `%25$VC_AIQUM_clone_191124%25` En Unified Manager. Debe conservar una nota de este problema cuando consulta una máquina virtual con un nombre que tenga caracteres especiales en ella.

====
. Compruebe el estado de la máquina virtual. Los Estados de la máquina virtual se recuperan de vCenter. Están disponibles los siguientes Estados: Para obtener más información sobre estos Estados, consulte la documentación de VMware.
+
** Normal
** Advertencia
** Alerta
** Sin supervisión
** Desconocido


. Haga clic en la flecha hacia abajo junto a la máquina virtual para ver la vista de resumen de la topología de los componentes en las capas de computación, red y almacenamiento. Se resalta el nodo que tiene problemas de latencia. La vista de resumen muestra la peor latencia de los componentes. Por ejemplo, si una máquina virtual tiene más de un disco virtual, esta vista muestra el disco virtual que tiene la peor latencia entre todos los discos virtuales.
. Para analizar la latencia y el rendimiento del almacén de datos durante un período de tiempo, haga clic en el botón *Workload Analyzer* situado en la parte superior del icono del objeto del almacén de datos. Se va a la página Workload Analysis, donde puede seleccionar un rango de tiempo y ver los gráficos de rendimiento del almacén de datos. Para obtener más información acerca del analizador de cargas de trabajo, consulte _solución de problemas de cargas de trabajo mediante el analizador de cargas de trabajo_.
+
link:concept-troubleshooting-workloads-using-the-workload-analyzer.html["Solucionar problemas de cargas de trabajo mediante el analizador de cargas de trabajo"]





== Visualización de topología expandida

Es posible desglosar cada componente por separado para ver la topología expandida de la máquina virtual.

. En la vista de topología de resumen, haga clic en *Expand Topology*. Puede ver la topología detallada de cada componente por separado con los números de latencia de cada objeto. Si hay varios nodos en una categoría, por ejemplo, varios nodos en el almacén de datos o VMDK, el nodo con la peor latencia se resalta en rojo.
. Para comprobar la ruta de E/S de un objeto específico, haga clic en ese objeto para ver la ruta de E/S y la asignación correspondiente. Por ejemplo, para ver la asignación de un disco virtual, haga clic en el disco virtual para ver su asignación resaltada en el VMDK correspondiente. En caso de desfase en el rendimiento de estos componentes, puede recopilar más datos de ONTAP y solucionar el problema.
+
[NOTE]
====
No se informan las métricas para VMDK. En la topología, solo se muestran los nombres de VMDK, no las métricas.

====

