---
permalink: online-help/concept-network-interface-performance-explorer-page.html 
sidebar: sidebar 
keywords:  
summary: La página Performance/Network Interface Explorer proporciona información general detallada sobre el rendimiento de todas las LIF dentro de un clúster. 
---
= Página del Explorador de la interfaz de red/rendimiento
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La página Performance/Network Interface Explorer proporciona información general detallada sobre el rendimiento de todas las LIF dentro de un clúster.

La página Performance/Network Interface Explorer le permite realizar un seguimiento y comparar el rendimiento de la LIF durante un periodo de tiempo específico, lo cual le ayuda a solucionar problemas y ajustar su rendimiento.

Con la funcionalidad Ver y comparar puede comparar el rendimiento de esta interfaz de red con:

* Otros LIF que están en el mismo puerto
* Otros LIF que están en la misma SVM
* El puerto en el que reside el LIF
* La SVM en la que reside el LIF


La página Performance/Network Interface Explorer le permite:

* Ver los problemas relacionados con los umbrales y sus detalles
* Realizar un seguimiento y comparar los datos de rendimiento de LIF
* Investigar y solucionar problemas relacionados con los umbrales
* Investigue y solucione problemas de rendimiento

