---
permalink: online-help/reference-backup-settings-dialog-box.html 
sidebar: sidebar 
keywords:  
summary: Puede utilizar el cuadro de diálogo Backup Settings para especificar una ruta de backup y un número de retenciones y habilitar una programación de backup para una instancia de Unified Manager seleccionada. 
---
= Cuadro de diálogo Backup Settings
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede utilizar el cuadro de diálogo Backup Settings para especificar una ruta de backup y un número de retenciones y habilitar una programación de backup para una instancia de Unified Manager seleccionada.

Puede cambiar la siguiente configuración de copia de seguridad de la base de datos:

* *Ruta*
+
Especifica la ruta de acceso a la ubicación en la que almacena los archivos de copia de seguridad. En la siguiente tabla se especifica el formato de ruta de backup y las ubicaciones predeterminadas, para los diferentes sistemas operativos:

+
[cols="1a,1a"]
|===
| Sistema operativo del host | Formato de ruta de copia de seguridad 


 a| 
Dispositivo virtual
 a| 
`/opt/netapp/data/ocum-backup`



 a| 
Red Hat Enterprise Linux o CentOS
 a| 
`/data/ocum-backup`



 a| 
Microsoft Windows
 a| 
`C:\ProgramData\NetApp\OnCommandAppData\ocum\backup\`

|===
* *Recuento de retención*
+
Especifica la cantidad máxima de backups que debe retener Unified Manager. El valor predeterminado es diez.

* *Diario programado*
+
Especifica la programación de backup diario con la hora.

* *Semanal programado*
+
Especifica la programación de backups semanales con el día y la hora.

* *Ninguno*
+
Especifica que no se crearán backups.





== Botones de comando

* *Aplicar*
+
Guarda el archivo de copia de seguridad y cierra el cuadro de diálogo. Unified Manager guarda el archivo de backup en el siguiente formato: `um_um_version_backup_os_timestamp.7z`.


