---
settings:
  name: Active IQ Unified Manager 9.7
  internal:
    pdf_enabled: true
    lipi_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  versions:
  - version-number: '9.7'
    url: "/active-iq-unified-manager-97"
  - version-number: '9.9'
    url: "/active-iq-unified-manager-99"
  - version-number: '9.8'
    url: "/active-iq-unified-manager-98"
  langs: es-es,us-en,ja-jp,ko-kr,zh-cn,zh-tw,de-de,fr-fr,it-it
sidebar:
  entries:
  - title: Documentos de Active IQ Unified Manager 9.7
    url: "/index.html"
  - title: Notas de la versión
    url: "/release-notes.html"
  - title: Manos a la obra
    entries:
    - title: Instalación rápida para VMware vSphere
      url: "/install-vapp/qsg-vapp.html"
    - title: Instalación de inicio rápido para Linux
      url: "/install-linux/qsg-linux.html"
    - title: Instalación de inicio rápido para Windows
      url: "/install-windows/qsg-windows.html"
  - section: install-vapp
  - section: install-linux
  - section: install-windows
  - section: config
  - section: online-help
  - section: performance-checker
  - section: health-checker
  - section: data-protection
  - section: reporting
  - section: api-automation
  - title: Avisos legales
    url: "/reference-legal-notices.html"
homepage:
  tiles:
  - title: Manos a la obra
    links:
    - title: Notas de la versión
      url: "/release-notes.html"
    - title: Instalación rápida para VMware vSphere
      url: "/install-vapp/qsg-vapp.html"
    - title: Instalación de inicio rápido para Linux
      url: "/install-linux/qsg-linux.html"
    - title: Instalación de inicio rápido para Windows
      url: "/install-windows/qsg-windows.html"
  - title: Instale y configure Unified Manager
    links:
    - title: Instale y actualice en sistemas VMware vSphere
      url: "/install-vapp/concept-requirements-for-installing-unified-manager.html"
    - title: Instalación y actualización en sistemas Linux
      url: install-linux/concept-requirements-for-installing-unified-manager.html
    - title: Instalar y actualizar en sistemas Windows
      url: "/install-windows/concept-requirements-for-installing-unified-manager.html"
    - title: Configure Unified Manager
      url: "/config/concept-configuring-unified-manager.html"
  - title: Supervisión del rendimiento
    links:
    - title: Umbrales de rendimiento
      url: "/performance-checker/concept-managing-performance-thresholds.html"
    - title: Rendimiento del clúster
      url: performance-checker/concept-monitoring-cluster-performance-from-the-dashboard.html
    - title: Grupo de políticas de calidad de servicio
      url: "/performance-checker/concept-managing-performance-using-qos-policy-group-information.html"
    - title: Analizador de cargas de trabajo
      url: "/performance-checker/concept-troubleshooting-workloads-using-the-workload-analyzer.html"
    - title: Rendimiento de cargas de trabajo
      url: "/performance-checker/concept-collecting-data-and-monitoring-workload-performance.html"
    - title: Gestione el rendimiento
      url: performance-checker/concept-managing-performance-using-perf-capacity-and-available-iops-information.html
  - title: Supervisión del estado del almacenamiento y los objetos
    links:
    - title: Clústeres y estado de objetos del clúster
      url: online-help/concept-managing-and-monitoring-clusters-and-cluster-object-health.html
    - title: Umbrales de salud
      url: "/health-checker/concept-managing-health-thresholds.html"
    - title: Envíe mensajes de AutoSupport y paquetes de soporte
      url: health-checker/task-send-a-support-bundle-to-technical-support.html
  - title: Supervisión de la protección de datos
    links:
    - title: Configure la relación de protección
      url: "/data-protection/task-setting-up-protection-relationships-in-unified-manager.html"
    - title: Realizar una recuperación tras fallos y una conmutación tras recuperación
      url: data-protection/task-performing-a-protection-relationship-failover-and-failback.html
    - title: Gestione la relación de protección
      url: data-protection/concept-managing-and-monitoring-protection-relationships.html
    - title: Generar informes
      url: "/reporting/concept-unified-manager-reporting.html"
  - title: Utilice las API de REST
    links:
    - title: Manos a la obra
      url: "/api-automation/concept-api-url-and-categories.html"
    - title: Gestionar objetos de almacenamiento
      url: "/api-automation/concept-data-center-apis.html"
    - title: Acceda a las API de ONTAP
      url: "/api-automation/concept-gateway-apis.html"
    - title: Flujos de trabajo comunes
      url: "/api-automation/concept-workflow-intro.html"
    - title: Aprovisionar almacenamiento
      url: api-automation/concept-provisioning-workflow.html
  - title: Más recursos
    links:
    - title: Vídeos de Unified Manager
      url: https://www.youtube.com/playlist?list=PLdXI3bZJEw7mp3jFSg0IJgo3oeDQRY-Gl
    - title: Blogs de Unified Manager
      url: https://www.netapp.com/blog/#q=active%20iq%20unified%20manager&t=Blogs&sort=%40publish_date_mktg%20descending&layout=card&f:@facet_language_mktg=[English]
    - title: Documentación para la versión más reciente de Active IQ Unified Manager
      url: https://docs.netapp.com/us-en/active-iq-unified-manager/index.html
