---
permalink: reporting/concept-scheduling-reports.html 
sidebar: sidebar 
keywords:  
summary: Una vez que tenga la vista que desea reutilizar y compartir como un informe, puede programarla mediante Active IQ Unified Manager. Puede gestionar informes programados, cambiando los destinatarios y la frecuencia de distribución de cada programación de informes. 
---
= Programación de informes
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Una vez que tenga la vista que desea reutilizar y compartir como un informe, puede programarla mediante Active IQ Unified Manager. Puede gestionar informes programados, cambiando los destinatarios y la frecuencia de distribución de cada programación de informes.

Es posible programar la mayoría de las vistas o páginas de inventario en Unified Manager. Las excepciones son eventos, que son informes que puede descargar como archivos CSV, pero no puede programar eventos para regeneración y uso compartido. Tampoco puede descargar ni programar los paneles, los favoritos ni las páginas de configuración.

Puede programar las vistas incorporadas que desee personalizar. Puede elegir el tipo de archivo que desea enviar, ya sea CSV o PDF. Cuando programe un informe por primera vez, puede descargarlo y asignarlo como el único destinatario para verlo como lo verán sus destinatarios.
