---
permalink: install-windows/task-upgrading-to-unified-manager-on-microsoft-windows.html 
sidebar: sidebar 
keywords:  
summary: Puede actualizar Unified Manager 9.5 o 9.6 a 9.7 descargando y ejecutando el archivo de instalación en la plataforma Windows. 
---
= Actualizar Unified Manager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede actualizar Unified Manager 9.5 o 9.6 a 9.7 descargando y ejecutando el archivo de instalación en la plataforma Windows.



== Antes de empezar

* El sistema donde se actualiza Unified Manager debe cumplir con los requisitos del sistema y del software.
+
xref:concept-virtual-infrastructure-or-hardware-system-requirements.adoc[Requisitos del sistema de hardware]

+
xref:reference-windows-software-and-installation-requirements.adoc[Requisitos de instalación y software de Windows]

+
[NOTE]
====
A partir de Unified Manager 9.5, OpenJDK se proporciona en el paquete de instalación y se instala automáticamente. Oracle Java no es compatible a partir de Unified Manager 9.5.

====
+
[NOTE]
====
A partir de Unified Manager 9.4, se requiere Microsoft .NET 4.5.2 o superior. Asegúrese de tener instalada la versión correcta de .NET antes de iniciar la actualización.

====
* Debe tener privilegios de administrador de Windows. Asegúrese de que su nombre de usuario no comience con un signo de exclamación "'!`". Installation of Unified Manager might fail if the user name of user running the installation begins with "`!''.
* Debe tener credenciales válidas para iniciar sesión en el sitio de soporte de NetApp.
* Para evitar la pérdida de datos, debe haber creado un backup de la máquina de Unified Manager en caso de que haya un problema durante la actualización.
* Debe tener suficiente espacio en disco disponible para realizar la actualización.
+
El espacio disponible en la unidad de instalación debe ser 2.5 GB mayor que el tamaño del directorio de datos. La actualización se detiene y muestra un mensaje de error que indica la cantidad de espacio que debe añadirse si no hay suficiente espacio libre.

* Durante la actualización, es posible que se le solicite que confirme si desea mantener la configuración predeterminada anterior para conservar los datos de rendimiento durante 13 meses o si desea cambiarla a 6 meses. Al confirmar, se depuran los datos de rendimiento históricos después de 6 meses.
* Antes de realizar la actualización, debe cerrar cualquier archivo o carpeta abierta en `<InstallDir\>\JDK` y.. `MySQL Data Directory`.




== Acerca de esta tarea

Durante el proceso de actualización, Unified Manager no está disponible. Debe completar todas las operaciones en ejecución antes de actualizar Unified Manager.

Si Unified Manager se empareja con una instancia de OnCommand Workflow Automation y hay nuevas versiones del software disponibles para ambos productos, debe desconectar los productos y, a continuación, configurar una nueva conexión de Workflow Automation tras las actualizaciones. Si solo actualiza uno de los productos, deberá iniciar sesión en Workflow Automation tras la actualización y comprobar que aún se recopilen datos de Unified Manager.



== Pasos

. Inicie sesión en el sitio de soporte de NetApp y busque la página *Descargar* para instalar Unified Manager en la plataforma Windows.
+
https://mysupport.netapp.com/products/index.html[]

. Descargue el archivo de instalación de Unified Manager Windows en un directorio de destino en el sistema Windows.
. Haga clic con el botón derecho en y ejecute el ejecutable del instalador de Unified Manager `(.exe)` fichero como administrador.
+
Unified Manager le solicita el siguiente mensaje:

+
[listing]
----
This setup will perform an upgrade of Unified Manager. Do you want to continue?
----
. Haga clic en *Sí* y, a continuación, haga clic en *Siguiente*.
. Introduzca la contraseña de root MySQL8 que se estableció durante la instalación y, a continuación, haga clic en *Siguiente*.
. Inicie sesión en la interfaz de usuario web de Unified Manager y compruebe el número de versión.




== Después de terminar

[NOTE]
====
Para realizar una actualización silenciosa de Unified Manager, ejecute el siguiente comando: `ActiveIQUnifiedManager-<version\>.exe /s /v"MYSQL_PASSWORD=netapp21! /qn /l*v C:\install.log`

====