---
permalink: install-windows/task-upgrading-openjdk-on-windows-ocum.html 
sidebar: sidebar 
keywords: Active IQ Unified Manager 
summary: 'Puede actualizar a una versión más reciente de Java Runtime Environment \(JRE\) en el servidor Windows en el que está instalado Unified Manager para obtener soluciones para vulnerabilidades de seguridad.' 
---
= Actualización de JRE
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede realizar una actualización a una versión más reciente de Java Runtime Environment (JRE) en el servidor Windows en el que está instalado Unified Manager para obtener soluciones para vulnerabilidades de seguridad.



== Antes de empezar

Debe tener privilegios de administrador de Windows en el sistema en el que está instalado Unified Manager.



== Pasos

. Inicie sesión como usuario administrador en la máquina host de Unified Manager.
. Descargue la versión adecuada de Java (64 bits) del sitio JDK en el sistema de destino.
+
Por ejemplo, descargar `openjdk-11_windows-x64_bin.zip` de `+http://jdk.java.net/11/+`.

. Utilice la consola de servicios de Windows para detener los siguientes servicios de Unified Manager:
+
** Servicio de adquisición de NetApp Active IQ (OCIE-au)
** Servicio de servidores de gestión de Active IQ de NetApp (Oncommandsvc)


. Expanda el `zip` archivo.
. Copie los directorios y archivos del resultado `jdk` directorio (por ejemplo, `jdk-11.0.2` A la ubicación donde está instalado Java. Ejemplo: `C:\Program Files\NetApp\JDK\`
. Inicie los servicios de Unified Manager mediante la consola de servicios de Windows:
+
** Servicio de servidores de gestión de Active IQ de NetApp (Oncommandsvc)
** Servicio de adquisición de NetApp Active IQ (OCIE-au)



